# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('duration', models.IntegerField(max_length=10, verbose_name='days')),
                ('from_date', models.DateTimeField(verbose_name='Arrive')),
                ('to_date', models.DateTimeField(verbose_name='Depart')),
            ],
        ),
    ]
